[2019-07-09 19:59:56,069] INFO    : user 'true_coder' logged out
[2019-07-10 10:03:17,715] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:03:18,225] WARNING : Not Found: /favicon.ico
[2019-07-10 10:03:21,777] WARNING : Not Found: /favicon.ico
[2019-07-10 10:03:21,797] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(sorted(data.items()))
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:03:24,596] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(sorted(data.items()))
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:03:31,136] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(sorted(data.items()))
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:03:54,369] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:05:16,304] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:05:17,395] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    data = collections.OrderedDict(sorted(collections.Counter(obj.date_joined for obj in users)))
TypeError: 'datetime.datetime' object is not iterable
[2019-07-10 10:05:17,744] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    data = collections.OrderedDict(sorted(collections.Counter(obj.date_joined for obj in users)))
TypeError: 'datetime.datetime' object is not iterable
[2019-07-10 10:05:18,168] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    data = collections.OrderedDict(sorted(collections.Counter(obj.date_joined for obj in users)))
TypeError: 'datetime.datetime' object is not iterable
[2019-07-10 10:05:38,065] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
TypeError: 'datetime.datetime' object is not iterable
[2019-07-10 10:05:38,337] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:05:39,211] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 12, in registration
    data = collections.OrderedDict(sorted(collections.Counter(str(obj.date_joined) for obj in users)))
ValueError: too many values to unpack (expected 2)
[2019-07-10 10:05:39,259] WARNING : Not Found: /favicon.ico
[2019-07-10 10:05:39,860] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 12, in registration
    data = collections.OrderedDict(sorted(collections.Counter(str(obj.date_joined) for obj in users)))
ValueError: too many values to unpack (expected 2)
[2019-07-10 10:05:40,405] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 12, in registration
    data = collections.OrderedDict(sorted(collections.Counter(str(obj.date_joined) for obj in users)))
ValueError: too many values to unpack (expected 2)
[2019-07-10 10:08:57,519] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:09:00,856] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:49,177] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:09:51,126] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:51,152] WARNING : Not Found: /favicon.ico
[2019-07-10 10:09:52,482] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:53,089] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:53,330] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:53,501] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:53,674] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:53,863] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:54,000] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:54,170] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:54,356] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:55,657] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:55,983] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:56,296] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:56,560] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:56,726] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:09:56,750] WARNING : Not Found: /favicon.ico
[2019-07-10 10:10:04,246] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:10:04,922] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:10:05,199] ERROR   : Internal Server Error: /api/registration
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 560, in api
    return getattr(app.views_api, data)()
  File "/home/arcturus/Projects/sharewood/app/views_api.py", line 13, in registration
    return django.http.JsonResponse(data)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/http/response.py", line 552, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
[2019-07-10 10:10:05,258] WARNING : Not Found: /favicon.ico
[2019-07-10 10:10:38,364] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:11:50,138] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:12:10,487] WARNING : Not Found: /favicon.ico
[2019-07-10 10:13:11,145] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:13:37,200] INFO    : /home/arcturus/Projects/sharewood/app/views_api.py changed, reloading.
[2019-07-10 10:13:49,398] WARNING : Not Found: /favicon.ico
[2019-07-10 10:14:35,901] WARNING : Not Found: /favicon.ico
[2019-07-10 10:14:58,427] WARNING : Not Found: /favicon.ico
[2019-07-10 10:30:27,820] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:30:27,826] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:30:47,211] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:30:47,219] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:30:47,289] WARNING : Not Found: /favicon.ico
[2019-07-10 10:30:49,189] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:30:49,197] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:30:49,267] WARNING : Not Found: /favicon.ico
[2019-07-10 10:30:50,930] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:30:50,933] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:32:16,076] ERROR   : Internal Server Error: /admin/auth/user/add/
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: app_profile.bio

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/admin.py", line 99, in add_view
    return self._add_view(request, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/admin.py", line 126, in _add_view
    return super().add_view(request, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
    obj.save()
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/app/models.py", line 145, in create_user_profile
    Profile.objects.create(user=instance)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: app_profile.bio
[2019-07-10 10:32:24,909] WARNING : Not Found: /favicon.ico
[2019-07-10 10:32:33,715] ERROR   : Internal Server Error: /admin/auth/user/add/
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: app_profile.bio

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/admin.py", line 99, in add_view
    return self._add_view(request, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/admin.py", line 126, in _add_view
    return super().add_view(request, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1088, in save_model
    obj.save()
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/app/models.py", line 145, in create_user_profile
    Profile.objects.create(user=instance)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: app_profile.bio
[2019-07-10 10:35:16,380] WARNING : Not Found: /media/static/
[2019-07-10 10:35:27,619] WARNING : Not Found: /media/static/
[2019-07-10 10:35:27,686] WARNING : Not Found: /favicon.ico
[2019-07-10 10:35:37,003] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:35:42,517] WARNING : Not Found: /media/static/
[2019-07-10 10:35:45,021] WARNING : Not Found: /media/media/record_src/videoplayback
[2019-07-10 10:35:45,349] WARNING : Not Found: /favicon.ico
[2019-07-10 10:35:52,734] WARNING : Not Found: /media/static/
[2019-07-10 10:35:55,487] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:35:58,595] WARNING : Not Found: /media/static/
[2019-07-10 10:42:44,852] WARNING : Not Found: /media/static/
[2019-07-10 10:42:44,909] WARNING : Not Found: /favicon.ico
[2019-07-10 10:43:35,588] WARNING : Not Found: /favicon.ico
[2019-07-10 10:46:34,696] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:46:34,700] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:46:37,517] INFO    : user 'root' logged out
[2019-07-10 10:46:37,698] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:46:37,701] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:47:17,304] ERROR   : Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: app_profile.bio

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 120, in register
    reguser = django.contrib.auth.models.User.objects.create_user(username, email, password1)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/models.py", line 151, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/models.py", line 145, in _create_user
    user.save(using=self._db)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/app/models.py", line 145, in create_user_profile
    Profile.objects.create(user=instance)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: app_profile.bio
[2019-07-10 10:49:38,189] WARNING : failed registration attempt (existing username)
[2019-07-10 10:49:50,360] ERROR   : Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arcturus/Projects/sharewood/app/views.py", line 72, in login
    django.contrib.auth.login(request, user)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 132, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/models.py", line 20, in update_last_login
    user.save(update_fields=['last_login'])
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/arcturus/Projects/sharewood/app/models.py", line 150, in save_user_profile
    instance.profile.save()
  File "/home/arcturus/Projects/sharewood/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
[2019-07-10 10:49:51,464] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:52,299] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:52,458] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:52,611] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:52,753] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:52,927] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:53,864] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:49:54,054] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:50:14,962] WARNING : Forbidden (CSRF token missing or incorrect.): /login/
[2019-07-10 10:51:07,939] WARNING : Not Found: /favicon.ico
[2019-07-10 10:51:53,646] WARNING : Not Found: /record_src/ext.jpg
[2019-07-10 10:51:53,654] WARNING : Not Found: /record_src/python_main_pic.png
[2019-07-10 10:57:51,142] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:58:54,113] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:59:00,172] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:59:19,473] WARNING : Not Found: /media/media/record_src/Background_08.mov
[2019-07-10 10:59:26,021] WARNING : Not Found: /media/static/
[2019-07-10 11:00:00,596] WARNING : Not Found: /media/static/
[2019-07-10 11:00:03,271] WARNING : Not Found: /media/static/
[2019-07-10 11:00:03,573] WARNING : Not Found: /favicon.ico
[2019-07-10 11:00:04,129] WARNING : Not Found: /media/static/
[2019-07-10 11:00:04,785] WARNING : Not Found: /media/static/
[2019-07-10 11:00:05,347] WARNING : Not Found: /media/static/
[2019-07-10 11:00:05,894] WARNING : Not Found: /media/static/
[2019-07-10 11:00:06,242] WARNING : Not Found: /media/static/
[2019-07-10 11:00:06,448] WARNING : Not Found: /favicon.ico
[2019-07-10 11:00:06,799] WARNING : Not Found: /media/static/
[2019-07-10 11:00:08,294] WARNING : Not Found: /media/static/
[2019-07-10 11:00:09,031] WARNING : Not Found: /media/static/
[2019-07-10 11:04:03,647] WARNING : Not Found: /media/static/
[2019-07-10 11:04:13,445] WARNING : Not Found: /media/static/
[2019-07-10 11:04:22,806] WARNING : Not Found: /media/static/
[2019-07-10 11:04:24,046] WARNING : Not Found: /media/static/
[2019-07-10 11:04:24,565] WARNING : Not Found: /favicon.ico
[2019-07-10 11:04:25,010] WARNING : Not Found: /media/static/
[2019-07-10 11:05:43,948] WARNING : Not Found: /media/static/
[2019-07-10 11:05:46,310] WARNING : Not Found: /media/static/
[2019-07-10 11:06:38,235] WARNING : Not Found: /media/static/
[2019-07-10 11:07:08,385] WARNING : Not Found: /media/static/
[2019-07-10 11:07:19,932] WARNING : Not Found: /media/static/
[2019-07-10 11:07:21,814] WARNING : Not Found: /media/static/
[2019-07-10 11:07:22,619] WARNING : Not Found: /media/static/
[2019-07-10 11:07:23,730] WARNING : Not Found: /media/static/
[2019-07-10 11:07:24,703] WARNING : Not Found: /media/static/
[2019-07-10 11:07:25,113] WARNING : Not Found: /media/static/
[2019-07-10 11:07:25,485] WARNING : Not Found: /media/static/
[2019-07-10 11:07:25,960] WARNING : Not Found: /media/static/
[2019-07-10 11:07:27,670] WARNING : Not Found: /media/static/
[2019-07-10 11:07:29,045] WARNING : Not Found: /media/static/
[2019-07-10 11:07:30,947] WARNING : Not Found: /media/static/
[2019-07-10 11:07:31,317] WARNING : Not Found: /media/static/
[2019-07-10 11:07:31,739] WARNING : Not Found: /media/static/
[2019-07-10 11:07:32,382] WARNING : Not Found: /media/static/
[2019-07-10 11:07:33,009] WARNING : Not Found: /media/static/
[2019-07-10 11:07:33,490] WARNING : Not Found: /media/static/
[2019-07-10 11:07:34,324] WARNING : Not Found: /media/static/
[2019-07-10 11:07:34,526] WARNING : Not Found: /favicon.ico
[2019-07-10 11:07:35,763] WARNING : Not Found: /media/static/
[2019-07-10 11:07:36,160] WARNING : Not Found: /media/static/
[2019-07-10 11:07:38,358] WARNING : Not Found: /media/static/
[2019-07-10 11:07:39,155] WARNING : Not Found: /media/static/
[2019-07-10 11:07:39,372] WARNING : Not Found: /favicon.ico
[2019-07-10 11:07:55,298] WARNING : Not Found: /media/static/
[2019-07-10 11:07:55,712] WARNING : Not Found: /favicon.ico
[2019-07-10 11:07:56,415] WARNING : Not Found: /media/static/
